### PR TITLE
Added html report that uses bootstrap css and jquery to provide richer results

### PR DESCRIPTION
**Pull request by jscott-concord**
Added html report that uses bootstrap css and jquery to provide richer results

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nunit/nunit-transforms?pullRequest=15) <br/>All CLA requirements met.

**Comment by jscott-concord** [comment]
Not totally done with modifying this new file but I believe it already adds decent value for you to consider adding to the project?

**Comment by CharliePoole** [comment]
@jscott-concord Thanks for your contribution. Sorry it took so long to notice - nobody is monitoring this project these days and we were even thinking about archiving it, but maybe not if it's still attracting contributions.

Your transform looks great but you have added it to the folder containing one of my own contributions, which makes it look as if I'm maintaining and supporting it. The idea of this project is that each contributor supports what they submit.

I realize it wasn't clear at the time you submitted this PR and we have now updated the general readme to clarify that.

Would you mind modifying this so you create a new top-level folder with the transform, a README and (preferably) a license. The readme should tell people how to reach you with problems. You should also modify the README in the root adding a row to the table for yourself and your work.

**Comment by jscott-concord** [comment]
@CharliePoole happy to move to another folder, can you suggest folder name and location?

**Comment by CharliePoole** [comment]
@jscott-concord Keep the convention that transforms applying to nunit3 format output are in a folder "nunit3-xxx" and just give the folder a name that suits you. Follow file-naming conventions similar to nunit3-summary.

Your README.md probably only needs a paragraph telling what this transform produces. I plan to move the description of how to actually run transforms out of nunit3-summary and into the root. Your LICENSE can be either a text file like mine or a markdown file or be omitted if you include a link to an open source license (usually on opensource.org) in your README.

I don't want to mislead you here... the NUnit Core Team is still considering closing (archiving) this project. We're now discussing it. Problem is that it needs a maintainer. Do you have any interest in that?

**Comment by jscott-concord** [comment]
@CharliePoole thank you for the quick response and feedback. With Nunit no longer releasing a UI test runner and needing to store the console-based results in a way that is more consumable and can be stored away with the results, what are the alternative options? Maybe I went down the wrong path in implementing this and better options are available?

**Comment by CharliePoole** [comment]
@jscott-concord I'm not making the connection with a GUI runner, so you may need to help me out!

You're right that there is no longer a program equivalent to the NUnit V2 GUI as part of the NUnit project. As it happens, I produce a GUI runner for NUnit tests independently. See https://github.com/testcentric-org/testcentric-gui

The GUI gives an immediate visual display of the tests for use by developers but it doesn't really solve the problem of archiving results. In any case, it's usually the results of your CI runs that you want to archive and a GUI doesn't help there. The usual way of doing that is by saving the TestResult.xml (or other named) result file, which contains all the same info you would see in running a test interactively except for immediate error or process messages. Using the console runner, you may also save all text output by redirecting it to a file. Generally, folks put any saved text output along with the xml in a uniquely named folder for each run.

BTW, my own experience with transforming XML output is that the choice of XSLT or C# code is generally made based on the personal preference of the programmer. Frankly, I usually write code. Even though I  seeded this repository with its first transforms, I don't much like working with XML, so for more advanced transformation I usually just write a program in C#.

I can't really tell you the best way to go for your needs because (1) I don't know what those needs are and (2) I don't know how you like to work. :smile: Feel free to go either way or to try one way then the other. If you add this transform here, we will continue to keep up the repository so long as you remain available to help people who want to use it.

**Comment by CharliePoole** [comment]
@jscott-concord I've gone ahead and modified the README in the root as I said I would, as well as the one under nunit3-summary.

**Comment by CharliePoole** [comment]
@jscott-concord Were you planning to update the PR?

**Comment by jscott-concord** [comment]
Certainly, I just need to figure out how 😉. I am new to GitHub and GIT so any guidance would be appreciated.

**Comment by CharliePoole** [comment]
Just make changes on your branch and push as usual. The PR will get updated automatically. There are conflicts to resolve before merging because other contributions have changed. I'll take care of that part.

**Comment by jscott-concord** [comment]
@CharliePoole before I make those changes want to conform to your naming convention. Do you have a suggestion on the folder name? Assume something like nunit3-summary-bootstrap, nunit3-bootstrap ?

**Comment by jscott-concord** [comment]
@CharliePoole I think I got the changes pushed up. I named the folder nunit3-bootstrap. Please take a look and let me know if you would like me to name it something different or if I missed anything.

**Comment by CharliePoole** [comment]
@jscott-concord The naming is fine.

You created a new branch called `patch1` instead of pushing the same branch. So the PR, which is based on your `master` branch of NUnit-Trasforms didn't get updated.

Options...
1. Create a new PR from the patch1 branch.
2. Merge your patch1 branch into your master branch locally and push that.
3. If you'd prefer not to spend any more time on it, I can pull down your patch1 branch and integrate everything.

FYI, when working on a feature, we create a branch with an appropriate name and make all changes on that branch. We push it repeatedly and eventually create a PR as you did. Then, as changes are requested, we change that same branch and push it again. Eventually, it all gets merged in to master. If you decide to do more work, you again pull down master - or update the master branch you already have - and create a new feature branch for the new work. Rinse and repeat. :smile:

**Comment by jscott-concord** [comment]
@CharliePoole thank you for the guidance. I believe I got your steps correct. Take a look and if not please just make the corrections ;-)

**Comment by CharliePoole** [comment]
@jscott-concord Looks good! I'll merge it in. Thanks for your contribution.

**Comment by CharliePoole** [comment]
@jscott-concord Thanks again. I invited you as a maintainer, with write access to the repository in case anything needs to be fixed. I realize that you're new to GitHub, so check with me if you should need help.

**Pull request merged**
