### PR TITLE
Update of output template in nunit3-junit.xslt

### PR DESCRIPTION
**Pull request by pavlo-liapota**

### CODE REVIEW

**Comment by CharliePoole** [comment]
Please add a description that says what you are fixing, i.e. what is now wrong in the output and how it will change.

**Comment by pavlo-liapota** [comment]
I used this file (nunit3-junit.xslt) for transforming NUnit 3.7 XML result, so that it can be used in Jenkins.
My results contained following elements before transformation:
`<test-case id="1" name="TestName" ...>
  <output><![CDATA[SystemOutput]]></output>
</test-case>`
But transformed file contained empty `<system-out />` elements.
After my change transformation was correct `<system-out>SystemOutput</system-out>` and output displayed on Jenkins.

**Comment by CharliePoole** [comment]
Sounds good to me! 

@tenwit Do you want to merge this?

**Comment by tenwit** [comment]
Looks good, thanks for your help!

**Pull request merged**
